backend:
  name: git-gateway
  branch: main

media_folder: "uploads/product-images"
public_folder: "/uploads/product-images"

collections:
  - name: "products"
    label: "Products"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Product Name", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Product Image", name: "image", widget: "image" }
      - { label: "Buy Link", name: "buy_link", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }
